#!/usr/bin/env python3
"""Add the complete DH13 taxel layout to the dual-hand URDF.

The authoritative layout is the original DH13 MuJoCo hand model.  Its dense
taxel sites are already expressed in each tactile link's local metre frame;
the old ``.npy`` files are only a partial 540-point layout and are deliberately
not used here.
"""

from __future__ import annotations

import argparse
import math
import re
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np


MARKER = "<!-- Paxini tactile taxels: generated by add_paxini_taxels.py -->"
PACKAGE = "package://diana7_dual_dexh13_description/"
EXPECTED_TAXELS_PER_HAND = 1140
TAXEL_SITE_RE = re.compile(
    r"^(?:right_(?:index|middle|ring)_(?:ip|mp|dp)|thumb_(?:tip|pad))_site_p\d+$"
)


def rpy_matrix(rpy: str) -> np.ndarray:
    r, p, y = (float(v) for v in rpy.split())
    cr, sr = math.cos(r), math.sin(r)
    cp, sp = math.cos(p), math.sin(p)
    cy, sy = math.cos(y), math.sin(y)
    rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]])
    ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]])
    rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]])
    return rz @ ry @ rx


def transform_from_origin(element: ET.Element | None) -> np.ndarray:
    result = np.eye(4)
    if element is None:
        return result
    result[:3, :3] = rpy_matrix(element.get("rpy", "0 0 0"))
    result[:3, 3] = np.fromstring(element.get("xyz", "0 0 0"), sep=" ")
    return result


def rpy_from_matrix(matrix: np.ndarray) -> tuple[float, float, float]:
    """Inverse of Rz(yaw) @ Ry(pitch) @ Rx(roll), with gimbal fallback."""
    value = max(-1.0, min(1.0, -float(matrix[2, 0])))
    pitch = math.asin(value)
    cp = math.cos(pitch)
    if abs(cp) > 1e-8:
        roll = math.atan2(float(matrix[2, 1]), float(matrix[2, 2]))
        yaw = math.atan2(float(matrix[1, 0]), float(matrix[0, 0]))
    else:
        roll = 0.0
        yaw = math.atan2(float(-matrix[0, 1]), float(matrix[1, 1]))
    return roll, pitch, yaw


def fmt(value: float) -> str:
    if abs(value) < 5e-12:
        value = 0.0
    return f"{value:.9g}"


def make_origin(xyz: np.ndarray, rotation: np.ndarray) -> str:
    rpy = rpy_from_matrix(rotation)
    return f'xyz="{" ".join(fmt(float(v)) for v in xyz)}" rpy="{" ".join(fmt(v) for v in rpy)}"'


def link_transforms(root: ET.Element) -> dict[str, np.ndarray]:
    """Return q=0 transforms from each link to its immediate tree root."""
    joints: dict[str, tuple[str, np.ndarray]] = {}
    for joint in root.findall("joint"):
        parent = joint.find("parent")
        child = joint.find("child")
        if parent is not None and child is not None:
            joints[child.get("link", "")] = (parent.get("link", ""), transform_from_origin(joint.find("origin")))

    cache: dict[str, np.ndarray] = {}

    def resolve(link: str) -> np.ndarray:
        if link in cache:
            return cache[link]
        if link not in joints:
            cache[link] = np.eye(4)
            return cache[link]
        parent, transform = joints[link]
        cache[link] = resolve(parent) @ transform
        return cache[link]

    for link in root.findall("link"):
        resolve(link.get("name", ""))
    return cache


def source_element_text(element: ET.Element) -> str:
    text = ET.tostring(element, encoding="unicode")
    text = text.replace("package://DH13_left_palm_URDF/meshes/", PACKAGE + "meshes/left/")
    return text


def append_left_tactile_meshes(target: ET.Element, source: ET.Element) -> list[str]:
    existing = {link.get("name") for link in target.findall("link")}
    inserted: list[str] = []
    for source_link in source.findall("link"):
        name = source_link.get("name", "")
        if "tactile_link" not in name or name in existing:
            continue
        target.append(ET.fromstring(source_element_text(source_link)))
        inserted.append(name)
    for source_joint in source.findall("joint"):
        child = source_joint.find("child")
        if child is None or child.get("link") not in inserted:
            continue
        target.append(ET.fromstring(source_element_text(source_joint)))
    return inserted


def taxel_link(name: str, color: str) -> ET.Element:
    link = ET.Element("link", {"name": name})
    inertial = ET.SubElement(link, "inertial")
    ET.SubElement(inertial, "mass", {"value": "1e-9"})
    ET.SubElement(inertial, "inertia", {
        "ixx": "1e-15", "ixy": "0", "ixz": "0",
        "iyy": "1e-15", "iyz": "0", "izz": "1e-15",
    })
    visual = ET.SubElement(link, "visual")
    ET.SubElement(visual, "geometry").append(ET.Element("sphere", {"radius": "0.0007"}))
    material = ET.SubElement(visual, "material", {"name": f"paxini_taxel_{color}"})
    ET.SubElement(material, "color", {"rgba": "0.9 0.1 0.1 1" if color == "left" else "0.1 0.35 0.95 1"})
    return link


def taxel_joint(name: str, parent: str, child: str, xyz: np.ndarray, rotation: np.ndarray) -> ET.Element:
    joint = ET.Element("joint", {"name": name, "type": "fixed"})
    ET.SubElement(joint, "origin", {"xyz": " ".join(fmt(float(v)) for v in xyz), "rpy": " ".join(fmt(v) for v in rpy_from_matrix(rotation))})
    ET.SubElement(joint, "parent", {"link": parent})
    ET.SubElement(joint, "child", {"link": child})
    return joint


def dense_sites(source_mjcf: Path) -> list[tuple[str, str, np.ndarray]]:
    """Read the 1140 dense DH13 sites and their owning tactile bodies."""
    root = ET.parse(source_mjcf).getroot()
    result: list[tuple[str, str, np.ndarray]] = []

    def visit(body: ET.Element) -> None:
        body_name = body.get("name", "")
        for site in body.findall("site"):
            name = site.get("name", "")
            if not TAXEL_SITE_RE.match(name):
                continue
            position = np.fromstring(site.get("pos", "0 0 0"), sep=" ")
            if position.shape != (3,):
                raise ValueError(f"invalid taxel position on {name}: {site.get('pos')!r}")
            result.append((name, body_name, position))
        for child in body.findall("body"):
            visit(child)

    world_body = root.find("./worldbody/body")
    if world_body is None:
        raise ValueError(f"source MJCF has no worldbody hand: {source_mjcf}")
    visit(world_body)
    if len(result) != EXPECTED_TAXELS_PER_HAND:
        raise ValueError(
            f"expected {EXPECTED_TAXELS_PER_HAND} dense DH13 sites, found {len(result)} in {source_mjcf}"
        )
    return result


def add_taxels(target: ET.Element, source_mjcf: Path, hand: str) -> int:
    """Attach source MJCF site positions to matching left/right URDF links."""
    hand_color = hand
    prefix = f"{hand}_paxini_taxel"
    source_parent_alias = {"right_thumb_tip_sensor_frame": "right_thumb_tactile_link_1"}
    available_links = {link.get("name", "") for link in target.findall("link")}
    count = 0
    for source_name, source_parent, position in dense_sites(source_mjcf):
        source_parent = source_parent_alias.get(source_parent, source_parent)
        if not source_parent.startswith("right_"):
            raise ValueError(f"unexpected dense taxel parent {source_parent!r} for {source_name}")
        parent = hand + source_parent[len("right"):]
        if parent not in available_links:
            raise ValueError(f"missing target parent link {parent!r} for {source_name}")
        # The source MJCF uses metres and the same local tactile-link frames as
        # the URDF meshes.  Only the hand prefix changes for the mirrored hand.
        taxel_suffix = source_name[len("right_"):] if source_name.startswith("right_") else source_name
        taxel_name = f"{prefix}_{taxel_suffix}"
        target.append(taxel_link(taxel_name, hand_color))
        target.append(taxel_joint(f"{taxel_name}_joint", parent, taxel_name, position, np.eye(3)))
        count += 1
    return count


def remove_generated_taxels(target: ET.Element) -> None:
    """Allow regeneration by removing only previously generated taxel links."""
    taxel_links = {
        link.get("name") for link in target.findall("link") if "_paxini_taxel_" in link.get("name", "")
    }
    for element in list(target):
        if element.tag == "link" and element.get("name") in taxel_links:
            target.remove(element)
        elif element.tag == "joint":
            child = element.find("child")
            if child is not None and child.get("link") in taxel_links:
                target.remove(element)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", type=Path, default=Path("diana7_dual_dexh13_description/urdf/dual_diana7_dexh13.urdf"))
    parser.add_argument(
        "--source-urdf",
        type=Path,
        default=None,
        help="optional legacy left-hand URDF used only to copy missing tactile mesh links",
    )
    parser.add_argument(
        "--source-mjcf",
        type=Path,
        default=Path("dexh13_mjcf/reference/dh13_taxel_layout.xml"),
        help="repository-local MJCF layout containing the complete 1140-site DH13 layout",
    )
    args = parser.parse_args()

    target_tree = ET.parse(args.urdf)
    target = target_tree.getroot()
    remove_generated_taxels(target)

    generated_start = len(target)
    left_meshes = []
    if args.source_urdf is not None:
        source_tree = ET.parse(args.source_urdf)
        left_meshes = append_left_tactile_meshes(target, source_tree.getroot())
    # Serialize the cleaned tree so stale generated blocks from older script
    # versions cannot survive in the output text.
    base_xml = ET.tostring(target, encoding="unicode")
    line_sep = "\n"
    left_count = add_taxels(target, args.source_mjcf, "left")
    right_count = add_taxels(target, args.source_mjcf, "right")
    if (left_count, right_count) != (EXPECTED_TAXELS_PER_HAND, EXPECTED_TAXELS_PER_HAND):
        raise ValueError(f"expected 1140 taxels per hand, got left={left_count}, right={right_count}")

    generated = []
    generated.append(MARKER)
    generated.append(f"<!-- Added {len(left_meshes)} left tactile mesh links and {left_count + right_count} taxel frames (1140 per hand). -->")
    generated_nodes = list(target)[generated_start:]
    generated_xml = line_sep.join(ET.tostring(node, encoding="unicode").replace("\n", line_sep) for node in generated_nodes)
    tail = line_sep + line_sep.join(generated) + line_sep + generated_xml + line_sep
    if base_xml.count("</robot>") != 1:
        raise ValueError("expected exactly one </robot> closing tag")
    args.urdf.write_bytes(base_xml.replace("</robot>", tail + "</robot>", 1).encode())
    print(f"added {len(left_meshes)} left tactile meshes, {left_count} left taxels, {right_count} right taxels")


if __name__ == "__main__":
    main()
